/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTG0 (number 74), J3[5]/PTG0_GPIO7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_G_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_G_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_G_GPIO_PORT kGPIO_PORTG    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITPINS_LED_G_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_G_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_G_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_G_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTG1 (number 73), J3[1]/PTG1_GPIO6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_R_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_R_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_R_GPIO_PORT kGPIO_PORTG    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITPINS_LED_R_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_R_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_R_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_R_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTG2 (number 72), J3[3]/PTG2_GPIO5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_Y_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_Y_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_Y_GPIO_PORT kGPIO_PORTG    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITPINS_LED_Y_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_Y_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_Y_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_Y_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC0 (number 32), J3[4]/PTC0_A1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY_1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_1_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_KEY_1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY_1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY_1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY_1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC1 (number 31), J2[3]/J3[6]/PTC1_A2_PWM1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY_2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_2_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_KEY_2_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY_2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY_2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY_2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC2 (number 25), J3[8]/PTC2_A3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY_3_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_3_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_3_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_KEY_3_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY_3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY_3_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY_3_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTC3 (number 24), J3[10]/PTC3_A4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_KEY_4_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_4_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_KEY_4_GPIO_PORT kGPIO_PORTC    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITPINS_KEY_4_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_KEY_4_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_KEY_4_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_KEY_4_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTG3 (number 71), J4[15]/PTG3_GPIO4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PTG3_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_PTG3_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PTG3_GPIO_PORT kGPIO_PORTG    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITPINS_PTG3_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PTG3_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PTG3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PTG3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTA6 (number 46), J2[15]/PTA6_ANB0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PTA6_EX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PTA6_EX_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PTA6_EX_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA7 (number 45), J1[16]/J2[17]/PTA7_D7_ANB1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PTA7_EY_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PTA7_EY_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PTA7_EY_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA0 (number 62), J2[2]/PTA0_D8_T0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BUZ_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BUZ_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BUZ_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTH3 (number 34), PTH3_KEY1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BOARDKEY_1_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BOARDKEY_1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BOARDKEY_1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTH4 (number 33), PTH4_KEY2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BOARDKEY_2_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BOARDKEY_2_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BOARDKEY_2_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTG7 (number 50), D4[3]/PTG7_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PORT kGPIO_PORTG    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTG6 (number 51), D4[4]/PTG6_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PORT kGPIO_PORTG    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTG5 (number 52), D4[1]/PTG5_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PORT kGPIO_PORTG    /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORTC6 (number 64), J1[3]/PTC6_RXD1/UART1_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORTC7 (number 63), J1[1]/PTC7_TXD1/UART1_TX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORTA3 (number 59), J2[20]/PTA3_ACCEL_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCELPINS_ACCEL_SCL_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_SCL_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITACCELPINS_ACCEL_SCL_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTA2 (number 60), J2[18]/PTA2_ACCEL_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCELPINS_ACCEL_SDA_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_SDA_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITACCELPINS_ACCEL_SDA_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTD4 (number 56), PTD4_ACCEL_INT1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITACCELPINS_ACCEL_INT1_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_INT1_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_INT1_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITACCELPINS_ACCEL_INT1_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCELPINS_ACCEL_INT1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_INT1_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITACCELPINS_ACCEL_INT1_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTD3 (number 57), PTD3_ACCEL_INT2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITACCELPINS_ACCEL_INT2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_INT2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_INT2_GPIO_PORT kGPIO_PORTD    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITACCELPINS_ACCEL_INT2_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITACCELPINS_ACCEL_INT2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITACCELPINS_ACCEL_INT2_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITACCELPINS_ACCEL_INT2_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCELPins(void);

/*! @name PORTB7 (number 13), EXTAL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITOSCPINS_EXTAL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITOSCPINS_EXTAL_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITOSCPINS_EXTAL_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB6 (number 14), XTAL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITOSCPINS_XTAL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITOSCPINS_XTAL_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITOSCPINS_XTAL_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSCPins(void);

#define SOPT0_CLKOE_0b0 0x00u /*!<@brief Bus Clock Output Enable: Bus clock output is disabled on PTH2. */

/*! @name PORTE7 (number 6), J5[5]/U7[1]/PTE7_CONN/CAN_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCANPINS_CAN_TX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCANPINS_CAN_TX_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITCANPINS_CAN_TX_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTH2 (number 7), J5[4]/U7[4]/PTH2_CONN/CAN_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITCANPINS_CAN_RX_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITCANPINS_CAN_RX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITCANPINS_CAN_RX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCANPins(void);

/*! @name PORTB1 (number 41), J1[4]/PTB1_IRTX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITINFRAREDPINS_IRTX_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITINFRAREDPINS_IRTX_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITINFRAREDPINS_IRTX_GPIO_PORT kGPIO_PORTB    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITINFRAREDPINS_IRTX_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITINFRAREDPINS_IRTX_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITINFRAREDPINS_IRTX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITINFRAREDPINS_IRTX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTA1 (number 61), J1[10]/PTA1_D4_T1/PTA1_IRRX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITINFRAREDPINS_IRRX_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITINFRAREDPINS_IRRX_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITINFRAREDPINS_IRRX_GPIO_PORT kGPIO_PORTA    /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITINFRAREDPINS_IRRX_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITINFRAREDPINS_IRRX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITINFRAREDPINS_IRRX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITINFRAREDPINS_IRRX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitINFRAREDPins(void);

/*! @name PORTF4 (number 38), PTF4_THER
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITTHERPINS_THER_A_PORT PORTF               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITTHERPINS_THER_A_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITTHERPINS_THER_A_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTF5 (number 37), PTF5_THER
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITTHERPINS_THER_B_PORT PORTF               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITTHERPINS_THER_B_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITTHERPINS_THER_B_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTHERPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
